Discord:
  Token: ""
  Guild:
  ReportChannel:
  StaffChannel:

mysql:
  host: "localhost"
  user: "root"
  pass: "pass"
  port: "3306"
  db: "ProxyServerManager"

mongo:
  host: localhost
  user: root
  pass: password
  port: 27017
  db: template
  # You can set the uri as you like.
  uri: "?authSource=admin"