Discord:
  Token: ""
  Guild:
  ReportChannel:
  StaffChannel:

ProxyChecker:
  api:

mysql:
  host: "localhost"
  user: "root"
  pass: "pass"
  port: "3306"
  db: "ProxyServerManager"

mongo:
  host: "localhost"
  user: "root"
  pass: "pass"
  port: "27017"
  db: "ProxyServerManager"